name: Generate
on:
  push:
    branches: 
     - '*'
     - '!main'
#     paths:
#       - 'tags/*.yml'
#       - 'alias.yml'
#       - 'overwrite.yml'
jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate Merge YAML
        run: python3 .github/workflows/merge.py #2> problems.log
      - name: Commit to main
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add --all
          git status
          git remote -v
          git branch -r
          git commit --allow-empty -m "Automated merge"
          git push -v -f origin main
