name: Generate
on:
  push:
    branches: 
     - '*'
     - '!main'
jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v3
      - name: Set Git Credentials
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch -v --unshallow
          git pull -v --all
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Validate YAML here;
        run: echo TODO
      - name: Generate Merged YAML
        run: python3 .github/workflows/merge.py 2> problems.log
      - name: Commit to main
        run: |
          git add --all
          git commit --allow-empty -m "Automated merge"
          git checkout main
          git merge -X 'theirs' -v ${GITHUB_REF##*/}
          git push -v -f origin main
